server:
  port: 8080
#日志配置
logging:
  level:
    root: info
  file:
#数据库配置
spring:
  application:
      name: movie-convert
  datasource:
    url: jdbc:mysql://rm-2zezb9t4eu96n6o8bo.mysql.rds.aliyuncs.com:3306/marketing-back-main
    username: marketing_core
    password: Ziteng@MarketingCore2017
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      properties:
            hibernate:
              hbm2ddl:
                auto: validate
      show-sql: true
#redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${marketing.username}:${marketing.password}@127.0.0.1:8000/eureka/
  instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 5
      prefer-ip-address: true
      metadata-map:
              cluster: MAIN
#其他设置
marketing:
  username: marketing
  password: marketing2017
app-prefix:

--- #####################################投产环境####################################################
server:
  port: 9010
#spring配置
spring:
  profiles: prod
  application:
      name: movie-convert
#数据库配置
  datasource:
    url: jdbc:mysql://rm-2zezb9t4eu96n6o8b.mysql.rds.aliyuncs.com:3306/marketing_wexin_db
    username: marketing_busi
    password: Ziteng@Business2017
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      properties:
            hibernate:
              hbm2ddl:
                auto: validate
#redis配置
  redis:
    database: 0
    host: 10.165.126.80
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
#springcloud配置
eureka:
  client:
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${marketing.username}:${marketing.password}@10.165.126.80:8000/eureka/
  instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 5
      prefer-ip-address: true
      metadata-map:
        cluster: MAIN

#日志配置
logging:
  level:
    root: INFO
  file: /home/ziteng/workspace/marketing-business/movie-convert/logs/movie-convert.log
#其他设置
app-prefix: /where/${spring.application.name}
marketing:
  username: marketing
  password: marketing2017

